### ISSUE TITLE
Animated: `useNativeDriver` was not specified

### ISSUE THREAD

**Issue by emersonhsieh** [liangl1412/react-native-emoji-keyboard#2]
When I was using the package with React Native 0.62, I get the following YellowBox warning:

```
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to true or false.
```

**Comment by emersonhsieh** [comment]
I made a pull request: https://github.com/liangl1412/react-native-emoji-keyboard/pull/3

**Comment by liangl1412** [comment]
Merged, thank you
