### ISSUE TITLE
Crashing when changing tabs

### ISSUE THREAD

**Issue by drexelfitzrosh** [liangl1412/react-native-emoji-keyboard#6]
Changing tabs on the emoji board cause the app to crash any idea why?

**Comment by liangl1412** [comment]
Can you be more specific, what platform, what's the error you see, and it would much helpful if you can paste the code that you calling the component

**Comment by drexelfitzrosh** [comment]
I solved it by downgrading the react-native viewpager to V3...

**Comment by drexelfitzrosh** [comment]
Sorry for not being specific Im using RN 0.61 and running it on Android. I think the issue was V4 on viewpager is supporting ViewPager2
