### ISSUE TITLE
Emojis colors are transparent on android

### ISSUE THREAD

**Issue by luna-codes-dz** [liangl1412/react-native-emoji-keyboard#7]
Hello, 

The colors of emojis are transparent on android, can you please guide me on how to fix this issue ?

Thanks a lot and keep going

**Comment by liangl1412** [comment]
@luna-codes-dz the default emoji or custom emoji? do you have a screenshot

**Comment by nemanja-sljivic** [comment]
@liangl1412 It is actually for default emojis:
![image](https://user-images.githubusercontent.com/68843991/134185046-e85b140d-1fed-4c06-b92f-b467b1322d3d.png)
Adding
```
  emoji: {
        color: '#000000', //This color to emojis
        textAlign: 'center'
    },
```
inside `EmojiIcon.js` should solve it
